### ISSUE TITLE
Fikse source.html

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#103]
- [x] Information container skalerer ikke riktig

- [x] Endre farger til noe som matcher temaet bedre

- [x] Korte ned tekst i sidenav

- [x] Bilde container skalerer ikke riktig

- [x] Skrolling horisontalt må fjernes

- [x] Det er mulig å skrolle både siden og kildene. Helst burde det bare være mulig på siden

- [ ] Sette inn kilder, bilder, linker, etc.

- [x] Legge inn studentnummer

- [x] Flytte "Link til å laste ned word dokument" lenger inn på siden

- [ ] Legge inn pdf dokumenter av møtenotatene

- [ ] Legge inn en egen kategori for kodemøter under meeting notes

- [x] Fjerne hvit linje over footer

**Comment by OleJorgenKnoph** [comment]
Her må height på elementene (spess de to første) endres for å passe til innholdet
