### ISSUE TITLE
Minimum 95 på Checker.eii.eu

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#107]
Vi må ha minimum 95% på checker.eii.eu på alle sider. Legg til sjekkliste i kommentarfeltet under her hvis det er noe den klager på men som vi ikke vet hvordan skal fikses.

**Comment by OleJorgenKnoph** [comment]
- [ ] Home

- [ ] Challenge

- [ ] Solution

- [ ] App

- [ ] Sources

- [ ] FAQ

**Comment by VetEnd** [comment]
index score :99.1%

**Comment by krissmed** [comment]
http://checkers.eiii.eu/
