### ISSUE TITLE
Appstore?!

### ISSUE THREAD

**Issue by VetEnd** [krissmed/DAFE1200-Eksamen#113]
Tenkte kanskje vi kunne legge til noen sånne enten på index/footer/app siden 

![c2818ab2b2d2fc09f8ca95d417146da4](https://user-images.githubusercontent.com/72869965/99397450-5f826380-28e3-11eb-956a-7d0980ad2cff.png)

**Comment by krissmed** [comment]
Kan legge det til på app.html
