### ISSUE TITLE
Legge til en liten animasjon på read more knappen

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#114]
@OleJorgenKnoph Hadde det vært mulig å legge til en liten animasjon på read more?

**Comment by OleJorgenKnoph** [comment]
Vetle som har laget. Men ja, kan legge til no.
Tenker no litt sånn scale typ? Som popper litt ut @krissmed

**Comment by VetEnd** [comment]
ja, fullt mulig det
