### ISSUE TITLE
Hvit ved siden av teksten når man zoomer ut på telefon

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#115]

**Comment by krissmed** [comment]
![Screenshot_20201117-191031](https://user-images.githubusercontent.com/29783486/99429995-075e5800-2909-11eb-87be-c0c537eee91e.jpg)

**Comment by krissmed** [comment]
Jeg finner noen elementer som overlapper siden, men finner ingen som er like store som siden. .infoText og .headline strekker seg litt over siden, mulig at å fikse det kan hjelpe.

**Comment by krissmed** [comment]
Linje 6 i footer.css er hvertfall en del av problemet. Jeg tror videre at vi må fikse padding på infotext og width i .headline

**Comment by OleJorgenKnoph** [comment]
Menyen?

**Comment by OleJorgenKnoph** [comment]
Men jeg har ikke lagt inn breakpoint i index enda

**Comment by krissmed** [comment]
Det er jo allerede breakpoint i menyen

**Comment by krissmed** [comment]
Jeg laster opp den siste versjonen nå, som burde hvertfall delvis ha fikset problemet

**Comment by OleJorgenKnoph** [comment]
Nyd. Kan se på det i morgen.
Jeg driver med source nu
