### ISSUE TITLE
Bruk svg ikoner i stedet for bilder

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#118]
Når siden er så minimalistisk som den er, føler jeg ikke at noen bilde passer inn. Tror det er bedre å bruke minimalistiske ikoner slik som disse https://www.flaticon.com/search?word=app.

**Comment by OleJorgenKnoph** [comment]
Enig der faktisk. Blir litt mer stilrent og mindre "barnslig" og rotete. 
Da er det sikkert lettere å få samme dimensjoner også.
Bare finne ikoner som er passende
