### ISSUE TITLE
Endre forside HOME

### ISSUE THREAD

**Issue by OleJorgenKnoph** [krissmed/DAFE1200-Eksamen#125]
Bort med gandhi. Få inn logo og slagord

**Comment by VetEnd** [comment]
har vi et slagsord? eller skal vi finne på et?

**Comment by OleJorgenKnoph** [comment]
Finne på no

**Comment by OleJorgenKnoph** [comment]
Sleng ut alle forslag her

**Comment by krissmed** [comment]
https://www.shopify.com/tools/slogan-maker
https://www.oberlo.com/tools/slogan-generator
https://www.oberlo.com/tools/slogan-generator
