### ISSUE TITLE
Gjør teksten større på større skjermer

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#146]
![Skjermbilde](https://user-images.githubusercontent.com/29783486/99574305-7dc98b80-29d7-11eb-93f4-d7292c6df6e5.PNG)

**Comment by krissmed** [comment]
Noen muligheter:
 - Krympe skrift eller linjemellomrom på mindre skjermer og ha mer info

- Øke skriftstørrelsen på større skjermer

- Gjøre "slidene" mindre slik at vi ikke får så mye tomrom mellom overskrifter

Dersom vi får på plass en løsning for det vil det være ganske enkelt å legge til flere slides for å få med mer info. Det vi har i dag er for lite tror jeg

**Comment by OleJorgenKnoph** [comment]
[
![Skjermbilde 2020-11-30 kl  16 59 01](https://user-images.githubusercontent.com/70891970/100632650-61a9e080-332d-11eb-9105-a653258f9c01.png)
](url)

**Comment by krissmed** [comment]
![Skjermbilde](https://user-images.githubusercontent.com/29783486/100743413-8d37d400-33dc-11eb-981a-cb1b55b93d1b.PNG)
