### ISSUE TITLE
integrasjon av google maps 

### ISSUE THREAD

**Issue by VetEnd** [krissmed/DAFE1200-Eksamen#148]
Veldig komplisert, med api opplegget til google, samt også registering av app osv..... Google krever også betalingskonto så vet ikke om det er noe poeng å intigrere kartet

**Comment by krissmed** [comment]
Hmm, mener å huske at jeg har gjort det tidligere ved å bare legge inn en linje med kode på siden. Mulig de har endret det siden sist. Har du sjekket [denne](https://addmap.net/)?

**Comment by VetEnd** [comment]
Kan teste det
