### ISSUE TITLE
Ideer til forside på solution.html

### ISSUE THREAD

**Issue by VetEnd** [krissmed/DAFE1200-Eksamen#149]
Noen av dere som har en ide til hva jeg kan putte inn øverst på solution.html siden

![d125f8a63c032020be5547a58a8bf990](https://user-images.githubusercontent.com/72869965/99606405-fcd7b780-2a09-11eb-9917-d5cb15986145.png)

**Comment by OleJorgenKnoph** [comment]
Kan se det an. Men mulighet at du tar det som står på challenge.html. Også legger jeg inn der hvilket mål vi valgte.
Var vel det 13?

**Comment by VetEnd** [comment]
Ja det var vel nr 13. Den med fornybar energi

**Comment by krissmed** [comment]
Vi har flyttet bærekraftsmålet til challenge, ikke sant? Da bør vi finne noe å ha her. Helst ikke bilde eller video.

**Comment by OleJorgenKnoph** [comment]
Vi la til det som var på challenge inn der. Quote fra obama om å ta grep osv

**Comment by krissmed** [comment]
Vi bør hverfall fikse bakgrunnsfargen på sitatet. Tenker at det bør være det samme som resten av sliden
