### ISSUE TITLE
For liten tekst i headeren på stor skjerm

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#151]
![Skjermbilde](https://user-images.githubusercontent.com/29783486/100370330-60fc0c00-3006-11eb-808c-e0489cee6b96.PNG)

**Comment by OleJorgenKnoph** [comment]
![Skjermbilde 2020-11-28 kl  13 00 51](https://user-images.githubusercontent.com/70891970/100515060-c3c1e480-3179-11eb-95d5-13e0b4337325.png)

Funker bra på min 32tommer nå.
