### ISSUE TITLE
Fikse bildet på app.html

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#152]
<img width="1033" alt="Skjermbilde" src="https://user-images.githubusercontent.com/29783486/100444977-9fe49d00-30ac-11eb-822e-80bd703e1eac.PNG">

**Comment by krissmed** [comment]
@OleJorgenKnoph @VetEnd Dobbeltsjekk at det funker hos dere også

**Comment by OleJorgenKnoph** [comment]
Funker
