### ISSUE TITLE
Rydde og kommentere kode

### ISSUE THREAD

**Issue by OleJorgenKnoph** [krissmed/DAFE1200-Eksamen#158]

**Comment by OleJorgenKnoph** [comment]
- [ ] index.html

- [ ] challenge.html

- [ ] solution.html

- [ ] app.html

- [ ] sources.html

- [ ] contact.html

**Comment by OleJorgenKnoph** [comment]
- [ ] index.css

- [ ] challenge.css

- [ ] solution.css

- [ ] app.css

- [ ] sources.css

- [ ] contact.css

- [ ] footer.html

- [ ] header.html

**Comment by OleJorgenKnoph** [comment]
- [ ] contact.js

- [ ] header.js

- [ ] index.js

- [ ] indexSiteNav.js

- [ ] sourceSiteNav.js

- [ ] source.js

**Comment by krissmed** [comment]
Vi har allerede issues for dette (#45 #43). Bare sørg for å fjerne dem når vi blir ferdig med dette.

**Comment by krissmed** [comment]
https://purifycss.online/
