### ISSUE TITLE
Hamburger menyen

### ISSUE THREAD

**Issue by VetEnd** [krissmed/DAFE1200-Eksamen#160]
Gjenganger i alle testene på http://checkers.eiii.eu/, lurte på om dere kunne se på det ettersom at jeg ikke har vært borti hamburgermeny og ikke tørr å ødelegge noe 

![028670b1f10a1d9ac070e6508dbb25d9](https://user-images.githubusercontent.com/72869965/100517840-0a213e80-318e-11eb-98b6-78963c21c7c3.png)
![7e9f7ee00ae58c18f6ebdf878e7af8ef](https://user-images.githubusercontent.com/72869965/100517848-19a08780-318e-11eb-8fc1-f73c8a7763d0.png)

**Comment by OleJorgenKnoph** [comment]
Vært borti det. Jævli tåpelig feil, men løses ved å legge til dette attributtet i gjeldene linjer.

onkeypress="collapseHamMenu()"

Jeg legger de til på alt nå
