### ISSUE TITLE
Fikse bildeoverlapp på app.html

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#166]
![Skjermbilde](https://user-images.githubusercontent.com/29783486/100546326-16c29700-3261-11eb-8266-c3170449fd1b.PNG)

**Comment by krissmed** [comment]
Vi må legge til et eller breakpoint

**Comment by OleJorgenKnoph** [comment]
hva med å ta margin top litt mer

**Comment by krissmed** [comment]
Tenkte egentlig på den som stikker opp fra bunnen. Den på toppen har jeg egentlig ikke sett så mye på enda
