### ISSUE TITLE
Fikse overlapp av tekst på challenge

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#167]
![Skjermbilde](https://user-images.githubusercontent.com/29783486/100546717-24791c00-3263-11eb-9c2a-c716538438e7.PNG)

**Comment by krissmed** [comment]
Se på breakpointet i index (linje 280), for å lage et fast høyde dersom høyden blir liten

**Comment by OleJorgenKnoph** [comment]
Husker vi fiksa litt på det. Men trenger vi enda et breakpoint for en skjerm som er så lav? Kan bli mye unødvendig kode. 
Det passer jo på de minste telefonene

**Comment by OleJorgenKnoph** [comment]
Ordna
