### ISSUE TITLE
Får ikke til å sette bildene under teksten med breakpoint

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#169]
Jeg får ikke til å sette bildene under teksten på grunn av det ikke er en satt høyde, så slik som jeg har gjort det nå, må man legge til breakpoint både for høyde og bredde. Har dere noen ideer?

**Comment by OleJorgenKnoph** [comment]
Bildene kommer under teksten når man bredden blir mindre nå

**Comment by OleJorgenKnoph** [comment]
men må nok legge til breakpoint for høyden også da teksten ikke passer når høyden blir mindre

**Comment by krissmed** [comment]
Ja, teksten må nok inn før vi setter en høyde. Skal se om jeg kan få gjort dette i tilegg til teksten og bildene i kveld

**Comment by OleJorgenKnoph** [comment]
Ja nydelig. Så tester vi og finpusser småfeila i morgen

**Comment by krissmed** [comment]
Fungerte på pcen, men ikke på telefonen.
