### ISSUE TITLE
Får masse feil på app.html når jeg scroller

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#176]
![Skjermbilde](https://user-images.githubusercontent.com/29783486/100673826-6fc72380-3364-11eb-90e9-7c4e2200e944.PNG)

**Comment by OleJorgenKnoph** [comment]
Er sidemenyen. Når det kun er 4 punkter i app. Så har jeg jo 5 slides i challenge, så da finner den ikke det punktet. 
Men den har ikkeno å si på brukeropplevelse og funksjon
