### ISSUE TITLE
Fikse bildestørrelse etc

### ISSUE THREAD

**Issue by OleJorgenKnoph** [krissmed/DAFE1200-Eksamen#23]
https://developers.google.com/speed/pagespeed/insights/?hl=no

**Comment by OleJorgenKnoph** [comment]
Bør være passende til innholdet på siden. Så finn ut hva vi skal skrive for så finne passende bilder i like dimensjoner

**Comment by krissmed** [comment]
Enig. Dette blir nok noe av de siste vi gjør. Foreløpig kan vi bruke de bildene vi allerede har og eventuelt bytte dem ut når innholdet er ferdig

**Comment by krissmed** [comment]
Jeg skal komprimere og nedskalere bilder på app.html. Resten av bildene bør ikke være noe problem i og med at de er vektorgrafikk. Fjern også bilder og grafikk som ikke er i bruk. Lenket til #174
