### ISSUE TITLE
Skift bakgrunnsfarge

### ISSUE THREAD

**Issue by OleJorgenKnoph** [krissmed/DAFE1200-Eksamen#24]
på challenge etc.

**Comment by krissmed** [comment]
Denne er nesten ferdig, eneste problemet er at det er litt mellomrom mellom mainSite og challengeSite. Vu bør også se nøyere på hvilke farger vi skal bruke.
![Skjermbilde3](https://user-images.githubusercontent.com/29783486/98869547-3fc9e600-2472-11eb-96e9-d458bab08514.PNG)

**Comment by OleJorgenKnoph** [comment]
Fikset mellomrommet

**Comment by OleJorgenKnoph** [comment]
Føler fargene må være litt natur/miljø-relatert. Sjekk ut 1, 3, 4, 29 og 30 på denne siden. https://visme.co/blog/website-color-schemes/

**Comment by OleJorgenKnoph** [comment]
<img width="1256" alt="Skjermbilde 2020-11-12 kl  15 47 36" src="https://user-images.githubusercontent.com/70891970/98955231-f07dc700-24fe-11eb-9c3c-3138724c4b68.png">
https://color.a11y.com
