### ISSUE TITLE
Backgroundwindmills skalerer ikke til 100% width på store skjermer

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#25]
![Skjermbilde](https://user-images.githubusercontent.com/29783486/98853961-346ac080-245a-11eb-9e15-0ae3fb4fbea1.PNG)

**Comment by OleJorgenKnoph** [comment]
Tror dette skyldtes at bilde ikke kan bli større enn opprinnelig størrelse.(?)
Mulig løsning: width 100%?

**Comment by krissmed** [comment]
Ja, det kan funke, problemet blir da på mobil. Nå fungerer det fint med quote og underquote. Mulig at det enkleste vil være å fjerne bildet for nå og bare ha tekst.

**Comment by VetEnd** [comment]
gjorde om til video background
