### ISSUE TITLE
"Challenge" skroller til over siteMenu, ikke solution og app

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#29]
![Skjermbilde3](https://user-images.githubusercontent.com/29783486/98863764-21abb800-2469-11eb-8371-c1ceac29cee3.PNG)
![Skjermbilde2](https://user-images.githubusercontent.com/29783486/98863768-22444e80-2469-11eb-98a3-b0e21c1cee87.PNG)
![Skjermbilde](https://user-images.githubusercontent.com/29783486/98863771-22dce500-2469-11eb-9eca-34b1a32419f8.PNG)

**Comment by OleJorgenKnoph** [comment]
Fikset
