### ISSUE TITLE
Opprydding i CSS

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#43]
Å gjøre:

- [x] Fjerne alle overflødige mellomrom

- [x] Riktig antall tabs på elementer

- [ ] Kommentere og forklare hva koden gjør

- [x] Fjerne overflødig kommentering

- [x] Dele inn i ulike seksjoner (eks. header vs. footer)

- [x] Ikke ha mer enn en id, gjøre om id til klasse der det passer seg

- [x] Bytte ut id med klasse der csskoden er lik (pass på at href fortsatt fungerer).

**Comment by OleJorgenKnoph** [comment]
- [ ] index.css

- [ ] app.css

- [ ] challenge.css

- [ ] contact.css

- [ ] footer.css

- [ ] header.css

- [ ] solution.css

- [ ] sources.css
