### ISSUE TITLE
Å trykke på logoen bør laste inn siden på nytt

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#44]
Per nå flytter logoen i headeren deg bare til toppen med smooth scroll. Det beste hadde være at den tar deg til toppen med en gang ved laste inn siden på nytt. Denne trengs bare å gjøre dersom vi får ned innlastningstiden av nettsiden

**Comment by VetEnd** [comment]
Greit, tar det i etterpå

**Comment by krissmed** [comment]
> Greit, tar det etterpå

Trengs ikke, Ole fikset
