### ISSUE TITLE
Oppryddning i HTML

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#45]
- [x]  Riktig antall tabs på elementer

- [x] Kommentere og forklare hva koden gjør (lenket til #28)

- [x] Dele inn i ulike seksjoner ved hjelp av kommentarer

- [x] Sørge for at alle tags har en start og en slutt

- [x] Fjerne overflødige mellomrom

- [x] Fjerne overflødig kommentering

- [x] Fjerne utbrukte elementer

**Comment by OleJorgenKnoph** [comment]
- [ ] index.html

- [ ] challenge.html

- [ ] solution.html

- [ ] app.html

- [ ] sources.html

- [ ] contact.html

**Comment by krissmed** [comment]
IDer og klasser bør være på formen "welcomePage", i stedet for "welcome_page" eller "WelcomePage"
