### ISSUE TITLE
Dobble linje på navigasjonsbaren

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#5]
Dersom man er på en delside (eks. challenge) og tar musen over samme samme delside på navigasjonen vil det komme to linjer under hverandre.

Screenshot:
https://ibb.co/tB23c8P

**Comment by OleJorgenKnoph** [comment]
Will do!

**Comment by OleJorgenKnoph** [comment]
Mulighet: endre hover eller active klassen slik at den ene ikke lager border-bottom. Heller skifte farge/skalere ut eller annen måte å gi tilbakemelding på.

**Comment by krissmed** [comment]
@OleJorgenKnoph Mulig, men tror det beste ville vært om vi la begge linjene nøyaktig oppå hverandre. Men jeg vet ikke hvor enkelt det er med tanke på at navbaren skal være responsiv og vil oppføre seg forskjellig i ulike størrelser.

**Comment by krissmed** [comment]
@OleJorgenKnoph En annen ting er at de ikke er noen når man laster inn siden. Den kommer først når man scroller. Mulig at man bare kan legge den til å være på "home" ved oppstart, dersom man gjør at siden går til toppen når man laster inn på nytt
![Skjermbilde3](https://user-images.githubusercontent.com/29783486/98869137-971b8680-2471-11eb-8583-14c7cb5f774a.PNG)

**Comment by OleJorgenKnoph** [comment]
Fikset begge
