### ISSUE TITLE
Opprette en sidenav for navigasjon på siden

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#67]
https://www.w3schools.com/howto/howto_js_sidenav.asp
https://www.w3schools.com/howto/howto_css_sidenav_buttons.asp
https://www.w3schools.com/howto/howto_css_sidebar_icons.asp

**Comment by krissmed** [comment]
Den er opprettet nå og fungerer slik den skal. Jeg er fortsatt litt usikker på hvordan den skal se ut @OleJorgenKnoph @VetEnd Noen innspill?

**Comment by krissmed** [comment]
Spørsmålet er om hele sidemenyen skal gå ut, slik som den gjør nå, eller om bare hvert enkelt element skal gå ut

**Comment by OleJorgenKnoph** [comment]
Ser bra ut.
Tenker alle bør gå ut. Og kanskje legge til ikoner/bilde på høyresiden (den delen som stikker ut) som tydeliggjør at det er en meny.

**Comment by krissmed** [comment]
Noe sånn? https://iconmonstr.com/?s=menu

**Comment by OleJorgenKnoph** [comment]
Ja

**Comment by OleJorgenKnoph** [comment]
Jeg driver å fikser slik at headerMenu blir aktiv når trykket. og tenker å legge inn den sidenav´en i JS slik at bakgrunnsfargen skifter når de trykkes.

**Comment by OleJorgenKnoph** [comment]
Prøvde men fikk ikke til. Går det å få de ikonene helt til høyre slik at en ser de uten å hovere?

**Comment by krissmed** [comment]
> Prøvde men fikk ikke til. Går det å få de ikonene helt til høyre slik at en ser de uten å hovere?

Aktiv JS fungerer hos i sidemenyen. 

Jeg skal prøve å fikse ikonene i løpet av dagen

**Comment by krissmed** [comment]
Da bør ikonene være greie. Sjekk om det ser greit ut hos dere
