### ISSUE TITLE
Lage challenge.html

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#70]
Ta utgangspunkt i index.html og lag 4 "slides" som fyller siden

**Comment by krissmed** [comment]
#67 må gjøres først

**Comment by krissmed** [comment]
Lagt til layouten. Ider og sidenavinnhold er midleritidig og må endres.

**Comment by VetEnd** [comment]
#149

**Comment by krissmed** [comment]
@OleJorgenKnoph Er det noe som mangler? I så fall, hva?

**Comment by OleJorgenKnoph** [comment]
Egentlig ikkenoe. Ene sidemenyen blir aktiv samtidig så skal fikse det så closer jeg

> @OleJorgenKnoph Er det noe som mangler? I så fall, hva?

**Comment by OleJorgenKnoph** [comment]
Samme feilen går igjen på de andre sidene, så skal få ordna det i JS

**Comment by krissmed** [comment]
Tenker det er greit å opprett en egen issue på et hvis det er problem overalt.

**Comment by OleJorgenKnoph** [comment]
Fiksa nå. Mangler bare challengemenyen
