### ISSUE TITLE
Lage solution.html

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#71]
Ta utgangspunkt i index.html og lag 4 "slides" som fyller siden

**Comment by krissmed** [comment]
# 67 må gjøres først

**Comment by krissmed** [comment]
Lagt til layouten. Ider og sidenavinnhold er midleritidig og må endres.

**Comment by OleJorgenKnoph** [comment]
Føre inn innhold. Skriv bullshit om hvordan vår løsning relaterer til problemet (Climate change).
b.	Describes how the problem relates to the solution that you have identified. 
Dette står i oppgaven ^.

**Comment by VetEnd** [comment]
👍👍

**Comment by VetEnd** [comment]
#149

**Comment by VetEnd** [comment]
:)
