### ISSUE TITLE
Lage app.html

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#72]
Ta utgangspunkt i index.html og lag 4 "slides" som fyller siden

**Comment by krissmed** [comment]
#67 må gjøres først

**Comment by krissmed** [comment]
Lagt til layouten. Ider og sidenavinnhold er midleritidig og må endres.

**Comment by krissmed** [comment]
- [ ] Legge til bilder av appen

- [ ] Legge inn tekst til hver enkelt side

**Comment by OleJorgenKnoph** [comment]
Får du lagt inn tekst i dag @krissmed? Slik at vi får litt mer helhetlig bilde av nettside og innhold. Så kan vi pirke på småtinga i resten av koden og se hvordan ting ser ut mer riktig tekst

**Comment by krissmed** [comment]
Skal gjøre det når jeg kommer hjem. Får nok gjort det i løpet av kvelden. Alle bildene er ferdig så det blir bare å beskrive dem

**Comment by OleJorgenKnoph** [comment]
Perf
