### ISSUE TITLE
Legge til animasjon på til toppen knappen

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#74]
Slik som her:
http://student.cs.hioa.no/~s341894/FinalProject/app/problem.html

**Comment by krissmed** [comment]
@OleJorgenKnoph Hvis mulig, prøv å lage til toppen kanppen i html og css i stedet for å bruke bilde. Tenker at det vi gi oss en ekstra stjerne i boka hvis vi får det til

**Comment by OleJorgenKnoph** [comment]
Droppa knappen
