### ISSUE TITLE
Skrive dokumentasjonen som skal inn på siden

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#8]

**Comment by krissmed** [comment]
Dokumentasjonen kan legges inn her
https://docs.google.com/document/d/17f7F51pVL1DAXn44xmgSkOR7gI72jGsDWGyLxirZYA8/edit?usp=sharing

**Comment by VetEnd** [comment]
- [ ] challenge

- [ ] solution

- [ ] app
