### ISSUE TITLE
Endre vindmøllebildet på index til noe annet.

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#81]
Jeg tenker at det blir vanskelig med vindmøllebildet pga. 1 det ikke er stort nok til skjermer større enn 1080p 2 det gjør det mye vanskeligere å skalere forsiden og 3 det ser ganske standard ut. Jeg tenker at det er tre løsninger mulig løsninger:
1. Sette inn et større bilde
2. Sette inn en video (mange gode videoer her: https://www.pexels.com/search/videos/electricity/)
3. Fjerne bilde og ha kun tekst (slik som her http://student.cs.hioa.no/~s341894/FinalProject/app/problem.html)

**Comment by OleJorgenKnoph** [comment]
Enig. Finne en løsning som ikke gjør siden for treg. mtp det så er kanskje kun tekst (mulig å gjøre den litt dynamisk) beste løsning.

**Comment by krissmed** [comment]
Dersom vi fjerner bildet går også #25  bort

**Comment by VetEnd** [comment]
gjorde om til video background
