### ISSUE TITLE
Ide for sources.html

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#92]
Hadde det vært en ide å lage en sitenav som kollapser på sources. Føler at den vi har nå hermer veldig etter den andre oppgaven. Noen ideer:
https://www.w3schools.com/howto/howto_js_fullscreen_overlay.asp
https://www.w3schools.com/howto/howto_js_off-canvas.asp
https://www.w3schools.com/howto/howto_css_sidebar_icons.asp

**Comment by OleJorgenKnoph** [comment]
Ja er litt enig. Kan gjøre om sidemenyen til noe i den kategorien. 
Mulig vi kan ta samme som på forsiden. Slik at det blir en rød tråd gjennom siden og ikke for mye forskjellige menyer og animasjoner.

**Comment by krissmed** [comment]
Ja, kanskje det beste hadde vært å lage en lang side som kan navigeres med sidenav
