### ISSUE TITLE
Idé: text to speech

### ISSUE THREAD

**Issue by OleJorgenKnoph** [krissmed/DAFE1200-Eksamen#93]
Idé:
Gikk gjennom noen av powerpointene til Anthony. Og tror at en knapp for å lese opp teksten på siden treffer han i hjerterota. Isåfall ha vi lagd en side som passer for svaksynte osv. Tviler at fler har tenkt på det.
En tanke å leke med.
Utførelse: skrive inn teksten i google translate, ta opp og lagre mp3 fil.

Blir da noe vi evt gjør til slutt

**Comment by krissmed** [comment]
Smart, mulig at det finnes en eller annen API vi kan integrere i stedet, men vet ikke hva Ana synes om det. Alternativt kan Vetle spille inn 🤣

**Comment by OleJorgenKnoph** [comment]
Stemmer for det!

**Comment by krissmed** [comment]
Dette er noe vi kan bruke, hvis det blir litt vanskelig med google translate. 
https://www.naturalreaders.com/online/

**Comment by krissmed** [comment]
https://ttsmp3.com/
