### ISSUE TITLE
Fikse responsiveness på contact.html

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#94]
- [ ] Gjøre at sidenav ikke stikker så mye ut. Jeg tror dette blir litt vanskelig hvis vi skal fortsette å ha koden i header. Mulig at det hadde vært lettere å ha den i cssen til hver enkelt side. 
![Skjermbilde](https://user-images.githubusercontent.com/29783486/99157753-0d1b2a00-26cc-11eb-8cc9-ebf74605b995.PNG)

- [x] Få ansatte til å midtstilles når vinduet blir smalere.
![Skjermbilde2](https://user-images.githubusercontent.com/29783486/99157772-3936ab00-26cc-11eb-9930-444a1f492b38.PNG)

- [x] Legge inn et lite mellomrom mellom ansatte

**Comment by krissmed** [comment]
@VetEnd Alternativt kan vi fjerne employee divene og bare ha kontaktinfo. Vi kan også legge til et kart som viser til pilestredet 35 i stedet

**Comment by VetEnd** [comment]
Ja kan fungere det, tar det litt senere blir ferdig i løpet av kvelden
