### ISSUE TITLE
Solution siteMenu har sluttet å virke. Jeg klarer ikke å finne noen feil

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#95]

**Comment by krissmed** [comment]
På index

**Comment by OleJorgenKnoph** [comment]
Stirra på det drite her nå i 2t. Klarer ikke se at det er noen feil... men siden klarer visstnok ikke finne elementene som er deklarert i index.js.

**Comment by OleJorgenKnoph** [comment]
Går det an å gå tilbake å se på tidligere koder uten å slette nåværende? For den funka vel tidlig i går?
