### ISSUE TITLE
Legge til breakpoint på index

### ISSUE THREAD

**Issue by krissmed** [krissmed/DAFE1200-Eksamen#99]
- [x] Gjøre at teksten ikke blir mindre når siden blir det

- [x] Breakpoint som fjerner bildet og gjør teksten får teksten til å ta flere linjer

- [x] Øke ulike slides til auto når teksten tar mer enn 100vh

**Comment by krissmed** [comment]
Har forsøkt å fikse den siste men height:auto vil ikke fungere. Tenker at høyden derfor må hardkodes til en størrelse eller gjøre teksten mindre ved svært små vindustørrelser

**Comment by OleJorgenKnoph** [comment]
Må få inn ferdig text først
